import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Football Dashboard',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={`${inter.className} flex flex-col h-screen`}>
        <nav className='bg-gray-800 p-4 text-white'>
          <ul className='flex flex-col sm:flex-row space-y-2 sm:space-y-0 sm:space-x-4'>
            <li>
              <Link
                href='/'
                className='hover:bg-gray-700 px-3 py-1 rounded-md block text-center'
              >
                Home
              </Link>
            </li>
            <li>
              <Link
                href='/scoreboard'
                className='hover:bg-gray-700 px-3 py-1 rounded-md block text-center'
              >
                Scoreboard
              </Link>
            </li>
            <li>
              <Link
                href='/dashboard'
                className='hover:bg-gray-700 px-3 py-1 rounded-md block text-center'
              >
                Dashboard
              </Link>
            </li>
            <li>
              <Link
                href='/graphiql'
                className='hover:bg-gray-700 px-3 py-1 rounded-md block text-center'
              >
                GraphQL API
              </Link>
            </li>
            <li>
              <Link
                href='/database-erd'
                className='hover:bg-gray-700 px-3 py-1 rounded-md block text-center'
              >
                Database ERD
              </Link>
            </li>
            <li>
              <Link
                href='/warehouse-erd'
                className='hover:bg-gray-700 px-3 py-1 rounded-md block text-center'
              >
                Warehouse ERD
              </Link>
            </li>
          </ul>
        </nav>

        <main className='p-4 flex-grow '>{children}</main>
        <footer className='bg-gray-800 p-4 text-white mt-auto'>
          <p className='text-center'>Made by Stephen Jeranyama</p>
        </footer>
      </body>
    </html>
  )
}
