import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Football Dashboard',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
      <nav className="bg-gray-800 p-4 text-white">
          <ul className="flex space-x-4">
            <li>
              <Link href='/' className="hover:bg-gray-700 px-3 py-1 rounded-md">
                Home
              </Link>
            </li>
            <li>
              <Link href='/graphiql' className="hover:bg-gray-700 px-3 py-1 rounded-md">
                GraphQL API
              </Link>
            </li>
          </ul>
        </nav>
        <main className="p-4">{children}</main>
        <footer className="bg-gray-800 p-4 text-white mt-auto">My Footer</footer>
      </body>
    </html>
  )
}
